print ("                   TOKO MAINAN ANAK") 
print ("          ********************************")
Nama_Pembeli = input("Masukkan Nama Pembeli : ")
Kode_Mainan = input("Masukkan Kode Mainan : ")
Harga = input("Masukkan Harga : ")
Jumlah_beli = input("Masukkan Jumlah Beli : ")
print("======================================")
print("Nama Pembeli = ", Nama_Pembeli)
print("Kode Kue = ", Kode_Mainan)
print("Harga = ", Harga)
print("Jumlah Beli = ", Jumlah_beli)
print("Total = ", int(Harga) * int(Jumlah_beli))